### ISSUE TITLE
Update customer endpoint should also support email address as a parameter

### ISSUE THREAD

**Issue by nicolas-maalouf-cko** [checkout/checkout-net-library#27]
For now the library only supports using the customer ID whereas the actual API endpoint also supports using email addresses.
[Ref](https://docs.checkout.com/reference/merchant-api-reference/customers/update-customer)

`client.customerService.updateCustomer()` should be able to handle both customer IDs and email addresses

**Comment by philippe-leonhardt-cko** [comment]
`client.customerService.updateCustomer()` will only handle customer IDs.
Support for both, *customerId* and *customerEmail* is limited to `client.customerService.getCustomer()`.

[Docs](https://docs.checkout.com/reference/merchant-api-reference/customers/update-customer) shall be updated accordingly.
